# LobbyBalancer Configuration (https://www.spigotmc.org/resources/10788/)
# Read the comments, they are a very important part of the configuration
# To get support send me a private message with a description of the problem and the config file
# To easily paste the config file (and other relevant files) use the command /balancer paste
# Remember to set enabled under settings to true

# Providers of this plugin
# NONE: Returns no server
# DIRECT: Returns the only server in the list
# LOCALIZED: Returns the server that matches a region (testing)
# LOWEST: Returns the server with the least players online
# RANDOM: Returns a random server
# PROGRESSIVE: Returns the first server that is not full
# FILLER: Returns the server with the most players online that is not full

settings:
  # The plugin will be disabled as default
  enabled: false

  # Disable the messages the plugin prints out when loading
  silent-startup: false

  # Whether the plugin should ask you to update or not
  check-updates: true

  # Disable this to opt-out of the plugin sending stats
  submit-stats: true

  # Pings to the servers to see if they can be accessed or not
  server-check:
    # If this is disabled the players will connect to the first server available
    enabled: true

    # Use either CUSTOM or GENERIC, the first one generally works the best
    tactic: CUSTOM

    # The attempts before giving up on getting a server for a player
    attempts: 5

    # The interval between every round of checks
    interval: 10000

    # This prints info every time the plugin checks a server and prints its results
    print-info: false

    # The descriptions that mark a server as non accessible
    marker-descs: ["Server is not accessible", "Gamemode has already started"]

  # This will connect the player to a server of the parent of the section the player is kicked from
  reconnect-kick:
    # If this is enabled the kick reasons must still match for this to work
    enabled: true

    # If enabled, the reasons will work as a blacklist instead of a whitelist
    inverted: false

    # The reasons that determine if a player is reconnected or not, supports regex
    reasons: []

    # Sections where this feature is ignored
    ignored: []

    # This will make it so that the server the player is kicked from will be excluded
    exclude-from: true

    # This prints info every time a player gets kicked telling you the reason and if it matches the reasons
    print-info: false

    # The message the player is sent when kicked, comment it out to remove the message
    message: '&cYou have been kicked from &a{from} &cand you are being moved to &a{to}&c, reason: &a{reason}'

    # Override the behavior with rules
    rules: {}

  # This will connect the player to a server of the parent of the section the player is currently on
  fallback-command:
    # If this is disabled the command will not be registered
    enabled: true

    # The name of the command, make sure it does not interfere with other commands
    name: 'fallback'

    # The aliases of the command, make sure it does not interfere with other commands
    aliases: ['lobby', 'hub', 'back']

    # Leave this empty for no permission
    permission: ''

    # Sections where this command is ignored
    ignored: []

    # Whether the command can accept the name of a section as a target
    arguments: false

    # Override the behavior with rules
    rules: {}

  # This gets the country of a player and decides to which server the player should go
  # Country ISO codes: http://dev.maxmind.com/geoip/legacy/codes/iso3166/
  # WARNING: In testing stage
  geolocation:
    # If disabled the localized provider will choose a random server
    enabled: false

    # This prints info every time the plugin checks the country of a player (while being used)
    print-info: true

    # The rules for the localized provider, every section using it has to have a rule
    # The country must be the code as specified in the link above
    rules:
      practice:
        'EUPractice': ["Country1", "Country2"]
        'USPractice': ["Country3", "Country4"]

  # This will reload the plugin every time you execute /greload
  auto-reload: true

  # Support for getting the players connected to a server with RedisBungee
  redis-bungee: false

  # Assign a target to a player instead of looking every time for one
  # This is reset every time the player disconnects
  assign-targets: false

  # When a player is not in any section, the player will go to the principal section
  # This affects both the fallback command and reconnect kick features
  fallback-principal: true

  # Comment a message to disable it
  messages:
    connecting: '&aConnecting to {server}'
    failure: '&cCould not find a server to connect to'
    unavailable: '&cThis command cannot be executed on this server'
    unknown: '&cCould not find a section with that name'

# Here you have an example of what you can do with the sections
# It is recommended to create your own sections
# The plugin will print out info telling you if your config is right or not
# The best way to understand this is to play around with it
# You can use regex to match a set of servers
sections:
  general-lobbies:
    principal: true
    provider: RANDOM
    section-server: 'general-lobbies'
    servers: ["Lobby1", "Lobby2", "Lobby3"]
  eggwars-lobbies:
    parent: 'general-lobbies'
    section-server: 'eggwars-lobbies'
    servers: ["EWLobby1", "EWLobby2", "EWLobby3"]
  eggwars-games:
    provider: FILLER
    parent: 'eggwars-lobbies'
    servers: ["EW1", "EW2", "EW3", "EW4", "EW5"]
    section-command:
      name: 'playeggwars'
      permission: ''
      aliases: []
  skywars-lobbies:
    parent: 'general-lobbies'
    section-server: 'skywars-lobbies'
    servers: ["SWLobby1", "SWLobby2", "SWLobby3"]
  skywars-games:
    provider: FILLER
    parent: 'skywars-lobbies'
    servers: ["SW1", "SW2", "SW3", "SW4", "SW5"]
    section-command:
      name: 'playskywars'
      permission: ''
      aliases: []
  dummy-section:
    provider: RANDOM
    dummy: true
    parent: 'skywars-lobbies'
    section-server:
    servers: ["DS1"]
  practice:
    provider: LOCALIZED
    parent: 'general-lobbies'
    servers: ["EUPractice", "USPractice"]
    section-command:
      name: 'practice'
      permission: ''
      aliases: ["rektnoobs"]

# Do not modify this
version: '${project.version}'
